/* AUTO-GENERATED by tools/reggen.py — do not hand-edit. */
/* Source: configs/regs.yaml */
#ifndef VLAB_SOC_REGS_H
#define VLAB_SOC_REGS_H

#include <stdint.h>

#define VLAB_ROM_BASE  (0x00000000U)
#define VLAB_SRAM_BASE  (0x10000000U)
#define VLAB_UART_BASE  (0x20000000U)
#define VLAB_TIMER_BASE  (0x20001000U)
#define VLAB_DMA_BASE  (0x20002000U)
#define VLAB_INTC_BASE  (0x20003000U)
#define VLAB_PERF_BASE  (0x20004000U)

#define VLAB_IRQ_UART  (0U)
#define VLAB_IRQ_TIMER  (1U)
#define VLAB_IRQ_DMA  (2U)

#define VLAB_DMA_CTRL  (0x2000200CU)  /* RW reset=0x00000000 */
#define VLAB_DMA_DST  (0x20002004U)  /* RW reset=0x00000000 */
#define VLAB_DMA_ERR_CODE  (0x20002018U)  /* RO reset=0x00000000 */
#define VLAB_DMA_IRQ_CLEAR  (0x20002014U)  /* WO reset=0x00000000 */
#define VLAB_DMA_LEN  (0x20002008U)  /* RW reset=0x00000000 */
#define VLAB_DMA_SRC  (0x20002000U)  /* RW reset=0x00000000 */
#define VLAB_DMA_STATUS  (0x20002010U)  /* RO reset=0x00000000 */
#define VLAB_INTC_ACK  (0x20003008U)  /* RO reset=0xFFFFFFFF */
#define VLAB_INTC_ACTIVE  (0x20003010U)  /* RO reset=0x00000000 */
#define VLAB_INTC_CLEAR  (0x2000300CU)  /* WO reset=0x00000000 */
#define VLAB_INTC_ENABLE  (0x20003000U)  /* RW reset=0x00000000 */
#define VLAB_INTC_PENDING  (0x20003004U)  /* RO reset=0x00000000 */
#define VLAB_PERF_CTRL  (0x20004014U)  /* RW reset=0x00000000 */
#define VLAB_PERF_CYCLES  (0x20004000U)  /* RW reset=0x00000000 */
#define VLAB_PERF_DMA_BYTES  (0x20004008U)  /* RW reset=0x00000000 */
#define VLAB_PERF_IRQ_COUNT  (0x2000400CU)  /* RW reset=0x00000000 */
#define VLAB_PERF_MEM_ACC  (0x20004004U)  /* RW reset=0x00000000 */
#define VLAB_PERF_STALLS  (0x20004010U)  /* RW reset=0x00000000 */
#define VLAB_TIMER_CTRL  (0x20001000U)  /* RW reset=0x00000000 */
#define VLAB_TIMER_IRQ_CLEAR  (0x20001010U)  /* WO reset=0x00000000 */
#define VLAB_TIMER_IRQ_STATUS  (0x2000100CU)  /* RW reset=0x00000000 */
#define VLAB_TIMER_LOAD  (0x20001004U)  /* RW reset=0x00000000 */
#define VLAB_TIMER_VALUE  (0x20001008U)  /* RO reset=0x00000000 */
#define VLAB_UART_BAUDDIV  (0x20000010U)  /* RW reset=0x00000000 */
#define VLAB_UART_CTRL  (0x2000000CU)  /* RW reset=0x00000000 */
#define VLAB_UART_RXDATA  (0x20000004U)  /* RO reset=0x00000000 */
#define VLAB_UART_STATUS  (0x20000008U)  /* RO reset=0x00000002 */
#define VLAB_UART_TXDATA  (0x20000000U)  /* WO reset=0x00000000 */

/* UART_STATUS bits */
#define VLAB_UART_STATUS_TX_BUSY  (1U << 0)
#define VLAB_UART_STATUS_TX_EMPTY (1U << 1)
#define VLAB_UART_STATUS_RX_VALID (1U << 2)
#define VLAB_UART_CTRL_ENABLE     (1U << 0)

/* TIMER_CTRL bits */
#define VLAB_TIMER_CTRL_ENABLE      (1U << 0)
#define VLAB_TIMER_CTRL_PERIODIC    (1U << 1)
#define VLAB_TIMER_CTRL_IRQ_ENABLE  (1U << 2)
#define VLAB_TIMER_IRQ_FIRED        (1U << 0)

/* DMA_CTRL / STATUS bits */
#define VLAB_DMA_CTRL_START       (1U << 0)
#define VLAB_DMA_CTRL_IRQ_ENABLE  (1U << 1)
#define VLAB_DMA_STATUS_BUSY   (1U << 0)
#define VLAB_DMA_STATUS_DONE   (1U << 1)
#define VLAB_DMA_STATUS_ERROR  (1U << 2)

/* PERF_CTRL bits */
#define VLAB_PERF_CTRL_ENABLE  (1U << 0)
#define VLAB_PERF_CTRL_RESET   (1U << 1)

#define VLAB_IRQ_NONE  (0xFFFFFFFFU)

#endif /* VLAB_SOC_REGS_H */
