#!/usr/bin/env python3
"""reggen: generate firmware/include/soc_regs.h from configs/regs.yaml.

Single source of truth for addresses so Python models and C firmware
can never diverge. Run:

    python3 tools/reggen.py

Reads configs/regs.yaml, writes firmware/include/soc_regs.h.
Fails loudly on missing bases/registers.
"""
from __future__ import annotations

import pathlib
import sys

try:
    import yaml
except ImportError:
    print("reggen: missing pyyaml (pip install -r requirements.txt)", file=sys.stderr)
    raise

ROOT = pathlib.Path(__file__).resolve().parent.parent
REGS_YAML = ROOT / "configs" / "regs.yaml"
OUT_H = ROOT / "firmware" / "include" / "soc_regs.h"


def main() -> int:
    data = yaml.safe_load(REGS_YAML.read_text())
    bases = data["bases"]
    registers = data["registers"]
    irq_lines = data.get("irq_lines", {})

    lines: list[str] = []
    lines.append("/* AUTO-GENERATED by tools/reggen.py — do not hand-edit. */")
    lines.append("/* Source: configs/regs.yaml */")
    lines.append("#ifndef VLAB_SOC_REGS_H")
    lines.append("#define VLAB_SOC_REGS_H")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("")
    for name, addr in bases.items():
        lines.append(f"#define VLAB_{name}_BASE  (0x{addr:08X}U)")
    lines.append("")
    for irq, num in irq_lines.items():
        lines.append(f"#define VLAB_IRQ_{irq}  ({int(num)}U)")
    lines.append("")
    for name, reg in sorted(registers.items()):
        base_name = reg["base"]
        offset = int(reg["offset"])
        addr = int(bases[base_name]) + offset
        lines.append(f"#define VLAB_{name}  (0x{addr:08X}U)  /* {reg['access']} reset=0x{int(reg['reset']):08X} */")
    lines.append("")
    # Bit definitions (contract, mirrors docs/soc-spec.md)
    lines.append("/* UART_STATUS bits */")
    lines.append("#define VLAB_UART_STATUS_TX_BUSY  (1U << 0)")
    lines.append("#define VLAB_UART_STATUS_TX_EMPTY (1U << 1)")
    lines.append("#define VLAB_UART_STATUS_RX_VALID (1U << 2)")
    lines.append("#define VLAB_UART_CTRL_ENABLE     (1U << 0)")
    lines.append("")
    lines.append("/* TIMER_CTRL bits */")
    lines.append("#define VLAB_TIMER_CTRL_ENABLE      (1U << 0)")
    lines.append("#define VLAB_TIMER_CTRL_PERIODIC    (1U << 1)")
    lines.append("#define VLAB_TIMER_CTRL_IRQ_ENABLE  (1U << 2)")
    lines.append("#define VLAB_TIMER_IRQ_FIRED        (1U << 0)")
    lines.append("")
    lines.append("/* DMA_CTRL / STATUS bits */")
    lines.append("#define VLAB_DMA_CTRL_START       (1U << 0)")
    lines.append("#define VLAB_DMA_CTRL_IRQ_ENABLE  (1U << 1)")
    lines.append("#define VLAB_DMA_STATUS_BUSY   (1U << 0)")
    lines.append("#define VLAB_DMA_STATUS_DONE   (1U << 1)")
    lines.append("#define VLAB_DMA_STATUS_ERROR  (1U << 2)")
    lines.append("")
    lines.append("/* PERF_CTRL bits */")
    lines.append("#define VLAB_PERF_CTRL_ENABLE  (1U << 0)")
    lines.append("#define VLAB_PERF_CTRL_RESET   (1U << 1)")
    lines.append("")
    lines.append("#define VLAB_IRQ_NONE  (0xFFFFFFFFU)")
    lines.append("")
    lines.append("#endif /* VLAB_SOC_REGS_H */")
    lines.append("")

    OUT_H.parent.mkdir(parents=True, exist_ok=True)
    OUT_H.write_text("\n".join(lines))
    print(f"reggen: wrote {OUT_H} ({len(registers)} registers)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
